#! /bin/csh

#ifort  -o selnodesort selnodesort.f
#./selnodesort
ifort -O2 -o p12345 p12345.f
./p12345
cp vep.res saf716_2_29695.vep.res
#mv selnode.velo selnode.saf12.Lock101.50k.tl.velo

#tar czvf res.tgz res.fl* slip grid.txt res.txt
tar czvf res.tgz res.fl*  *.vep.res

#rm stop slip grid.txt res.txt

cp res.tgz ../results/saf716_2_29695.tgz
rcp res.tgz jiyang@geo01:/home/jiyang/Dropbox/SAF/model/saf716/saf716_2_29695.tgz
#rcp res.tgz jiyang@geo01:/home/jiyang/Dropbox/SAF/model/saf12/results/saf12.Lock101.50k.tgz
#rcp selnode.saf12.Lock101.50k.tl.velo jiyang@geo01:/home/jiyang/Dropbox/SAF/model/saf12/post/.
#rcp selnode.saf12.1870.bl.velo jiyang@geo01:/home/jiyang/Dropbox/SAF/model/saf12/post/.
