#! /bin/csh

tar xzvf data0.tgz
./umcazpartition

rm stop disp-vect* curve* part?.fl* part??.fl*

#bsub -n 12 -a mvapich "mpirun.lsf ./ddmliq1 >fout"
cp ddmliq1 saf716_2
nohup mpirun -np 48 -machinefile hosts ./saf716_2 > saf716_2.log &


